import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sideBar";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/components/Auth/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} text-foreground bg-muted antialiased`}
      >
        <AuthProvider>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full px-2 md:pl-0">
            <div className="py-2">
              <SidebarTrigger variant={"outline"} size={"lg"} />
            </div>
            {children}
          </main>
          <Toaster />
        </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
