###
GET http://localhost:3002/accounts

###
POST http://localhost:3002/register
Content-Type: application/json

{
    "username": "john",
    "password": "test123",
    "user_role": "Admin",
    "first_name": "john",
    "last_name": "lewis",  
     "email": "johnlewis20@gmail.com"
}

###
POST http://localhost:3002/signin
Content-Type: application/json

{
   "email": "johnlewis20@gmail.com",
   "password": "test123"
   
}