###
GET http://localhost:3002/accounts

###
POST http://localhost:3002/register
Content-Type: application/json

{
    "username": "dave3456",
    "password": "test123",
    "user_role": "Member",
    "first_name": "dave",
    "last_name": "chapelle",  
     "email": "davechapelle20@gmail.com"
}

###
POST http://localhost:3002/signin
Content-Type: application/json

{
   "email": "johnlewis20@gmail.com",
   "password": "test123"
   
}
//admin email - johnlewis20@gmail.com
//member email - davechapelle20@gmail.com
//password - test123