# version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
    image: authentication
    ports:
      - "3002:3002"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: db  # Using the service name as the host
      DB_USER: user123
      DB_PASSWORD: password123
      DB_NAME: db123
