version: '3.8'

services:
  reservation-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
